version: "3"

services:
  postgres:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=nest"
      - "POSTGRES_PASSWORD=123456"
    expose:
      - "5432"
    ports:
      - "5432:5432"
