version: '3.5'

services:
  postgres:
    container_name: delivery-postgres
    image: postgres:12.5
    environment:
      POSTGRES_USER: ${DATABASE_CONNECTION}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - "${DATABASE_PORT}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
